### ISSUE TITLE
add code to this repo

### ISSUE THREAD

**Issue by sheilasaia** [advancedag/dse-yield-tutorial#1]
@ImmediateStranger, when you get a chance can you please add your code, notebooks, and setup scripts for the yield tutorial to this repository? I'd like us to keep it all in one place and putting it here will help us stay organized. happy to walk through with you how to create a branch on your local computer, push that to this directory, and submit a pull request to merge your additions into the main branch.

**Comment by HoffmanGeospatial** [comment]
Yes absolutely, but I believe I still need Write Privileges activated. (I get the message, "Uploads are disabled. File uploads require push access to this repository".)

**Comment by HoffmanGeospatial** [comment]
@sheilasaia Doneskiis! 😀
